services:
  playwright:
    build:
      context: ./playwright-server
      dockerfile: Dockerfile
    ports:
      - "5900:5900"       # VNC port for remote display
      - "6080:6080"       # noVNC Web UI
      - "9222:9222"       # WebSocket endpoint for Playwright
    hostname: playwright
    environment:
      - DISPLAY=:99


  backend:
    depends_on:
      - playwright
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    hostname: backend
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PLAYWRIGHT_WS_ENDPOINT=ws://playwright:9222/ws-endpoint

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    hostname: frontend
